# Generated by Django 5.2.16 on 2026-07-15 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('github_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('default_branch', models.CharField(max_length=100)),
                ('private', models.BooleanField(default=False)),
                ('stars', models.IntegerField(default=0)),
                ('forks', models.IntegerField(default=0)),
                ('html_url', models.URLField()),
                ('github_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='authentication.githubaccount')),
            ],
            options={
                'db_table': 'repositories',
            },
        ),
    ]
