# Generated by Django 5.2.16 on 2026-07-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='repository',
            name='open_issues',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='repository',
            name='forks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='repository',
            name='stars',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
