# Generated by Django 5.2.16 on 2026-07-16 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='github_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='github_username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_url',
        ),
    ]
