# Generated by Django 5.2.16 on 2026-07-18 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0003_delete_aireviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary', models.TextField()),
                ('strengths', models.JSONField(default=list)),
                ('issues', models.JSONField(default=list)),
                ('suggestions', models.JSONField(default=list)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('model_name', models.CharField(default='gpt_5.5', max_length=100)),
                ('pull_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_review', to='reviews.pullrequest')),
            ],
            options={
                'db_table': 'ai_reviews',
            },
        ),
    ]
