# Generated by Django 6.0.7 on 2026-07-30 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('reviews', '0003_delete_aireviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AiReviews',
            new_name='AIReview',
        ),
        migrations.CreateModel(
            name='AIFileReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_path', models.CharField(max_length=500)),
                ('file_status', models.CharField(choices=[('added', 'Added'), ('modified', 'Modified'), ('deleted', 'Deleted')], max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('strengths', models.JSONField(default=list)),
                ('issues', models.JSONField(default=list)),
                ('suggestions', models.JSONField(default=list)),
                ('ai_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_reviews', to='ai.aireview')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
