# Generated by Django 5.2.16 on 2026-07-15 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('github_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('profile_url', models.URLField()),
                ('access_token', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'github_accounts',
            },
        ),
    ]
