# Generated by Django 5.2.16 on 2026-07-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubaccount',
            name='avatar_url',
            field=models.URLField(blank=True),
        ),
    ]
