# Generated by Django 5.2.16 on 2026-07-16 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_githubaccount_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubaccount',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
