# Generated by Django 5.2.16 on 2026-07-17 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0002_alter_repository_options_repository_open_issues_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('github_pr_id', models.BigIntegerField(unique=True)),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('state', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=255)),
                ('base_branch', models.CharField(max_length=255)),
                ('head_branch', models.CharField(max_length=255)),
                ('html_url', models.URLField()),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='repositories.repository')),
            ],
            options={
                'db_table': 'pull_requests',
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='AiReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary', models.TextField()),
                ('strengths', models.JSONField(default=list)),
                ('issues', models.JSONField(default=list)),
                ('suggestions', models.JSONField(default=list)),
                ('scores', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('model_name', models.CharField(default='gpt_5.5', max_length=100)),
                ('pull_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_review', to='reviews.pullrequest')),
            ],
            options={
                'db_table': 'ai_reviews',
            },
        ),
    ]
