# Generated by Django 5.2.16 on 2026-07-18 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aireviews',
            old_name='scores',
            new_name='score',
        ),
    ]
