# Generated by Django 5.2.16 on 2026-07-18 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_scores_aireviews_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AiReviews',
        ),
    ]
